PhamtomjsService:
  phantomjsPath: "/Users/apple/Work/phantomjs-2.1.1-macosx/bin/phantomjs"

PrivilegeLoginService:
  url: "https://testprivilege.newcms.ws.netease.com"
  corpid: "//*[@id=\"id_corpid\"]"
  corppw: "//*[@id=\"id_corppw\"]"
  corpbtn: "//*[@id=\"corp\"]/form/div[4]/button"
  loginSuccess: "//*[@id=\"projectList\"]"
  projectUrl: "https://testprivilege.newcms.ws.netease.com/admin/project/intoProject?projectToken=56B1E580C3504552B61556B9DD002691&_id=%s"

StorageProperties:
  location: "upload-dir"

ProjectInfo:
  projectToken: "56B1E580C3504552B61556B9DD002691"
  projectKey: "ccneteasecomcmsprivilege"
  authApi: "/authc/app/login"
