WechatAccessProperty:
  appid: wxd15360f7ddacbaec
  secret: 78a5ecfb17044008c068ad41b82f975c
  tokenUrl: https://api.weixin.qq.com/cgi-bin/token
  qrCodeUrl: https://api.weixin.qq.com/cgi-bin/qrcode/create?access_token=%s
  expire_seconds: 86400
  action_name: QR_LIMIT_STR_SCENE
  charset: UTF-8
  grant_type: client_credential
  ticketUrl: https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=%s
  userInfoUrl: https://api.weixin.qq.com/cgi-bin/user/info
  menuUrl: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=%s

Button:
  button:
    赛乐维:
      - url: "https://spring.io/guides/tutorials/bookmarks/"
        name: "赛乐维官网"
        type: "view"
      - url: "https://shop.jd.hk/?shopId=672044"
        name: "京东商城"
        type: "view"
      - url: "https://spring.io/guides/tutorials/bookmarks/"
        name: "往期精彩"
        type: "view"
    客户中心:
      - url: "https://spring.io/guides/tutorials/bookmarks/"
        name: "分销规则"
        type: "view"
      - url: "https://spring.io/guides/tutorials/bookmarks/"
        name: "常见问题"
        type: "view"
      - url: "https://spring.io/guides/tutorials/bookmarks/"
        name: "客服咨询"
        type: "view"
    活动有礼:
      - url: "https://spring.io/guides/tutorials/bookmarks/"
        name: "客户反馈表"
        type: "view"
      - url: "https://spring.io/guides/tutorials/bookmarks/"
        name: "客户调研表"
        type: "view"
      - key: "KEY_INVITE"
        name: "生成邀请码"
        type: "click"

WechatCustomerProperty:
  add: https://api.weixin.qq.com/customservice/kfaccount/add?access_token=%s
  update: https://api.weixin.qq.com/customservice/kfaccount/update?access_token=%s
  del: https://api.weixin.qq.com/customservice/kfaccount/del?access_token=%s
  getkflist: https://api.weixin.qq.com/cgi-bin/customservice/getkflist?access_token=%s

WechatMaterialProperty:
  batchget_material: https://api.weixin.qq.com/cgi-bin/material/batchget_material?access_token=%s

ShareServiceProperty:
  shareLink: /wechat/material/share?url=%s&imgUrl=%s