WechatAccessProperty:
  appid: wxd15360f7ddacbaec
  secret: 78a5ecfb17044008c068ad41b82f975c
  tokenUrl: https://api.weixin.qq.com/cgi-bin/token
  qrCodeUrl: https://api.weixin.qq.com/cgi-bin/qrcode/create?access_token=%s
  expire_seconds: 86400
  action_name: QR_LIMIT_STR_SCENE
  charset: UTF-8
  grant_type: client_credential
  ticketUrl: https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=%s
  userInfoUrl: https://api.weixin.qq.com/cgi-bin/user/info
  menuUrl: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=%s

Button:
  button:
    赛乐维:
      - url: "http://55951118.m.weimob.com/vshop/Index?PageId=541725&channel=menu"
        name: "赛乐维官网"
        type: "view"
      - url: "https://shop.jd.hk/?shopId=672044"
        name: "京东商城"
        type: "view"
      - url: "https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzUzODAwNDA0Ng==&scene=123#wechat_redirect"
        name: "往期精彩"
        type: "view"
    客户中心:
      - key: "KEY_INVITE"
        name: "生成邀请码"
        type: "click"
      - url: "http://mp.weixin.qq.com/s/UAG06wtMcqk9VpFhKF0cqg"
        name: "分销规则"
        type: "view"
      - url: "http://55951118.m.weimob.com/weisite/list?pid=55951118&bid=57129306&wechatid=fromUsername&ltid=2232545&wxref=mp.weixin.qq.com&channel=menu"
        name: "常见问题"
        type: "view"
      - url: "http://55951118.im.m.weimob.com/?aid=55951118&channel=menu"
        name: "客服咨询"
        type: "view"
    活动有礼:
      - url: "https://sojump.com/jq/15835781.aspx"
        name: "客户反馈表"
        type: "view"
      - url: "https://sojump.com/jq/15850998.aspx"
        name: "客户调研表"
        type: "view"




WechatCustomerProperty:
  add: https://api.weixin.qq.com/customservice/kfaccount/add?access_token=%s
  update: https://api.weixin.qq.com/customservice/kfaccount/update?access_token=%s
  del: https://api.weixin.qq.com/customservice/kfaccount/del?access_token=%s
  getkflist: https://api.weixin.qq.com/cgi-bin/customservice/getkflist?access_token=%s

WechatMaterialProperty:
  batchget_material: https://api.weixin.qq.com/cgi-bin/material/batchget_material?access_token=%s

ShareServiceProperty:
  shareLink: /wechat/material/share?url=%s&imgUrl=%s
  listLink: http://www.kurkuma.cn/wechat/material/list?qrUrl=%s
  cutImg: https://mmbiz.qpic.cn/mmbiz_png/OoxQeTGnyxEcLLD37qEYmdphyUrzCtqyJtnEKuU8utvMu1VC2sic2UMTd8JibeyBD8x6OxHuV0cZIuC7ibYGFOz0A/0?wx_fmt=png
  proxyUrl: /wechat/material/imgUrl?url=

WebdriverProperty:
  startUrl: https://shop.jd.com/index.action
  qrCodeXpath : //*[@id="content"]/div/div[1]/div/div[4]/div/div[2]/div[1]/div/img
  iframeSrc: //*[@id="loginFrame"]
  authXpath: //*[@id="account-login"]
  userXpath: //*[@id="loginname"]
  passXpath: //*[@id="nloginpwd"]
  loginXpath: //*[@id="paipaiLoginSubmit"]
  verificationCode: //*[@id="authcode"]
  verificationImg: //*[@id="JD_Verification1"]
  smsVerification: //*[@id="tab_phoneV"]
  successUrl: //*[@id="_og_showContent"]
  userName: sk303694
  password: c168136355
  phantomjsPath: /Users/apple/Work/phantomjs-2.1.1-macosx/bin/phantomjs

OrderProperty:
  orderList: https://order.shop.jd.com/order/sSopUp_allList.action?page=%s
  totalPage: /html/body/div[2]/div/div[3]/div[1]/div/div/div[2]/div[3]/div/input[1]
  limitPage: /html/body/div[2]/div/div[3]/div[1]/div/div/div[2]/div[3]/div/input[2]
  detailTel: //*[@id="viewOrderMobile"]
